- name: Delete EC2 instance
  hosts: local
  connection: local
  gather_facts: false
  vars_files:
    - Variables.yml
  tasks:
  - name: Terminating {{ec2_id}} instance in {{aws_region}}
    local_action:
      module: ec2
      region: "{{aws_region}}"
      wait: true
      instance_ids: "{{ec2_id}}"
      state: "absent"
